### ISSUE TITLE
Verify KYLIN-4485 & KYLIN-4419

### ISSUE THREAD

**Issue by zzcclp** [zzcclp/Kylin-works#1]
### Check list
- [x] Step 1. [**OPTIONAL**]Understand background/root cause/design basically(one hour EST) . Its issue type is 
    - [ ] bug fix
    - [x] new feature
    - [x] enhancement
- [x] Step 2. Test cases are designed and documented (30 minutes EST).
- [x] Step 3. Prepare specific env, for example:
    - mock data (maybe some specific data type)
    - test env (maybe install a RDBMS instance).
- [x] Step 4. Verify and make sure test cases passed.
- [x] Step 5. Paste manual important steps and screenshots here (20 minutes EST). 
    - If you find difficulty in pick most important evidence, please attach diagnosis package. 
- [ ] Step 6. Do more check in user perspective (20 minutes EST)
    - [ ] Doc need be updated? And if it is updated? Ask help for release manager if so.
    - [ ] If it is a breaking change so we should notify Kylin community? Ask help for release manager if so.
- [x] Step 7.  Summarize this test (20 minutes EST).

### Total estimate
- 4 hours for small issue from optimistic estimate. 

### Note
If you find some unexpected and **unrelated** error/mistake, please DO report it if it is truly a mistake, I think we may research and fix it in the future.

If you find background information/root cause analysis is not complete or ambiguous, please try to contact to author or do a quick research and record what you find. It is a good chance to learn something interesting.

If you find it is not easy to design testcase, please notify release manager.

**Comment by zzcclp** [comment]
## Background
Please see the [description](https://issues.apache.org/jira/browse/KYLIN-4485) of KYLIN-4485.

### New properties:
- kylin.cube.migration.enabled
Specifies whether to show 'Migrate', 'Approve Migration' and 'Reject Migration' in "Action" drop-down list for cube management, the default value is false;
- kylin.metadata.model-schema-updater-checker-enabled
Specifies whether to check for model schema update when check check model compatibility, the default value is false;
- kylin.metadata.able-change-string-to-datetime
Specifies whether to enable to convert String to Date or Time when check table schema update, the default value is false;
- kylin.cube.rowkey-encoding-auto-convert
Specifies whether to enable to convert date/time dictionary on date/time/varchar column to DimensionEncoding implicitly, the default value is true;
- kylin.server.self-discovery-enabled
Specifies whether to enable to discover kylin instance from zookeeper, the default value is false;
- kylin.cube.migration.expansion-rate
Specifies the threshold value of expansion rate when check the quality of the cube, the default value is 5;
- kylin.cube.migration.query-generator-max-dimension-number
Specifies the max number of dimension column when generate sql for checking the quality of the cube, the default value is 3;
- kylin.cube.migration.rule-query-latency-enabled
Specifies whether to check query latency when check the quality of the cube, the default value is true;
- kylin.cube.migration.query-latency-seconds
Specifies the threshold value of query latency in seconds when check the quality of the cube, the default value is 2;
- kylin.cube.migration.query-latency-max-threads
Specifies the max number of query threads to execute sql when check the quality of the cube, the default value is 5;
- kylin.cube.migration.query-latency-iteration
Specifies the max number of query sql to be generated when check the quality of the cube, the default value is 5;
- kylin.cube.migration.source-address
Specifies the source address of kylin instance;
- kylin.cube.migration.target-address
Specifies the target address of kylin instance;
- kylin.cube.notification-mail-suffix
Specifies the default suffix address of email for sending notifications.

### Removed properties:
```
kylin.tool.auto-migrate-cube.enabled                          false
kylin.tool.auto-migrate-cube.copy-acl                         TRUE
kylin.tool.auto-migrate-cube.purge-src-cube            TRUE
kylin.tool.auto-migrate-cube.src-config
kylin.tool.auto-migrate-cube.dest-config
```

### New test cases:
```
TableSchemaUpdaterTest                           passed
ProbabilityGeneratorCLITest                      passed
QueryGeneratorCLITest                                passed
```

**Comment by zzcclp** [comment]
## Design test cases

### Prepare test env
- Three Kylin instances, two instances are on the same cluster (one as QA instance and the other as PROD instance), the third instance is on the other cluster, as PROD instance.
- Run sample.sh to create sample models and cubes on QA instances;

### Case-1
Use web UI to migrate cubes from QA env to PROD env on the same cluster.
#### Expected result
Migrate cubes from QA env to PROD env and then cubes can support to query successfully.

### Case-2
Use command to migrate cubes from QA env to PROD env on the different clusters.
#### Expected result
Migrate cubes from QA env to PROD env and then cubes can support to query successfully.

### Case-3
Support to modify data type from varchar to date and do not need to re-create cube.
#### Expected result
After modifying data type from varchar to date and then cubes can also support to query successfully.

**Comment by zzcclp** [comment]
## Prepare data and env
- [x] Built on commit_SHA: aa42d8c7fc590c8f68d35225eddcf0f7172310f8
- [x] Hadoop env: HDP 2.4
- [x] Added below properties into kylin.properties for QA env:
```
kylin.env=QA
kylin.metadata.url=kylin_4485_metadata_qa@hbase
kylin.storage.url=hbase
kylin.env.hdfs-working-dir=/kylin_4485_metadata_qa
kylin.storage.hbase.namespace=default
kylin.storage.hbase.table-name-prefix=KYLIN_4485_QA_
kylin.source.hive.intermediate-table-prefix=kylin_4485_qa_
kylin.source.hive.database-for-flat-table=kylin_4485_qa
kylin.cube.migration.enabled=true
kylin.server.self-discovery-enabled=true
kylin.metadata.model-schema-updater-checker-enabled=true
kylin.metadata.able-change-string-to-datetime=true
kylin.cube.rowkey-encoding-auto-convert=true
kylin.cube.migration.expansion-rate=5
kylin.cube.migration.query-generator-max-dimension-number=3
kylin.cube.migration.query-latency-seconds=2
kylin.cube.migration.query-latency-max-threads=5
kylin.cube.migration.query-latency-iteration=5
kylin.cube.migration.source-address=sandbox.hortonworks.com:17070
kylin.cube.migration.target-address=sandbox.hortonworks.com:17777
kylin.cube.notification-mail-suffix=@kyligence.io
kylin.cube.migration.rule-query-latency-enabled=true
```

- [x] Added below properties into kylin.properties for PROD env on the same cluster:
```
kylin.env=PROD
kylin.metadata.url=kylin_4485_metadata_prod@hbase
kylin.storage.url=hbase
kylin.env.hdfs-working-dir=/kylin_4485_metadata_prod
kylin.storage.hbase.namespace=default
kylin.storage.hbase.table-name-prefix=KYLIN_4485_PROD_
kylin.source.hive.intermediate-table-prefix=kylin_4485_prod_
kylin.source.hive.database-for-flat-table=kylin_4485_prod
kylin.source.hive.keep-flat-table=false
kylin.env.zookeeper-base-path=/kylin
kylin.cube.migration.enabled=true
kylin.server.self-discovery-enabled=true
kylin.metadata.model-schema-updater-checker-enabled=true
kylin.metadata.able-change-string-to-datetime=true
kylin.cube.rowkey-encoding-auto-convert=true
kylin.cube.migration.expansion-rate=5
kylin.cube.migration.query-generator-max-dimension-number=3
kylin.cube.migration.query-latency-seconds=2
kylin.cube.migration.query-latency-max-threads=5
kylin.cube.migration.query-latency-iteration=5
kylin.cube.migration.source-address=sandbox.hortonworks.com:17777
kylin.cube.migration.target-address=sandbox.hortonworks.com:17070
kylin.cube.notification-mail-suffix=@kyligence.io
kylin.cube.migration.rule-query-latency-enabled=true
```

- [x] Added below properties into kylin.properties for PROD env on the other cluster:
```
kylin.env=PROD
kylin.metadata.url=kylin_4485_metadata_prod@hbase
kylin.storage.url=hbase
kylin.env.hdfs-working-dir=/kylin_4485_metadata_prod
kylin.storage.hbase.namespace=default
kylin.storage.hbase.table-name-prefix=KYLIN_4485_QA_
kylin.source.hive.intermediate-table-prefix=kylin_4485_qa_
kylin.source.hive.database-for-flat-table=kylin_4485_prod
kylin.source.hive.keep-flat-table=false
kylin.env.zookeeper-base-path=/kylin
kylin.cube.migration.enabled=true
kylin.server.self-discovery-enabled=true
kylin.metadata.model-schema-updater-checker-enabled=true
kylin.metadata.able-change-string-to-datetime=true
kylin.cube.rowkey-encoding-auto-convert=true
kylin.cube.migration.expansion-rate=5
kylin.cube.migration.query-generator-max-dimension-number=3
kylin.cube.migration.query-latency-seconds=2
kylin.cube.migration.query-latency-max-threads=5
kylin.cube.migration.query-latency-iteration=5
kylin.cube.migration.rule-query-latency-enabled=true
```

- [x] The cube you want to migrate is READY
<img width="1034" alt="cube_ready" src="https://user-images.githubusercontent.com/9430290/84133768-244d5000-aa7a-11ea-92bf-9492fe700679.png">

**Comment by zzcclp** [comment]
## Verify test cases - Case-2

**Comment by zzcclp** [comment]
## Verify test cases - Case-3

**Comment by zzcclp** [comment]
## Verify test cases - Case-1
1. Go to Kylin QA portal: [QA Kylin](http://10.1.2.13:17070/kylin), and find the cube you want to migrate from 'Model' page;
<img width="1034" alt="cube_ready" src="https://user-images.githubusercontent.com/9430290/84134906-d6d1e280-aa7b-11ea-8bea-4612f069e7e3.png">

2. Go to "Action" drop-down list and click "Migrate"
<img width="1034" alt="cube_ready" src="https://user-images.githubusercontent.com/9430290/84135052-100a5280-aa7c-11ea-83cd-887e8ec7f657.png">

#### Note
- The status of the cubes you want to migrate must be READY.
- The property 'kylin.cube.migration.enabled' must be set to true.

3. After you click "Migrate" button, you will see a pop-up window:
<img width="580" alt="cube_migration" src="https://user-images.githubusercontent.com/9430290/84137290-0d5d2c80-aa7f-11ea-85ac-cc7d14b27a52.png">

4. Enter the target project name and click "Validate" button to verify the cube validity.
<img width="580" alt="cube_migration" src="https://user-images.githubusercontent.com/9430290/84149290-ced16d00-aa92-11ea-8cb7-0c1a36afe10b.png">

#### Common exceptions and suggested solutions
- If the target project name don't exist on the PROD env, it will show the message as below:
<img width="474" alt="cube_invalid_target_project" src="https://user-images.githubusercontent.com/9430290/84156490-24f6de00-aa9c-11ea-9a97-7026c5f79df3.png">
Please enter the correct project name or create the expected project on the PROD env.


- 'Cube email notification list is not set or empty': please add notification email in the Notification List of cube;

#### Some suggestion messages(these messages just are some advises):
- _Auto merge time range for cube XXXX is not set_: if 'Auto Merge Threshold' is not set, this message will be shown. You can ignore it or set 'Auto Merge Threshold' in 'Refresh Setting' section of cube.
- _ExpansionRateRule: failed on expansion rate check with exceeding 5_: it means the expansion rate of the cube you want to migrate exceed 5, which is the value of property 'kylin.cube.migration.expansion-rate', you can set the proper value for the cube.
- _Failed on query latency check with average cost 5617 exceeding 2000ms_: if property 'kylin.cube.migration.rule-query-latency-enabled' is set to true, it will generate some test sql to test the average query latency for the cube you want to migrate. You can set the proper value for property 'kylin.cube.migration.query-latency-seconds';

5. After validations are ok and click 'Submit' button to send the migration request email to cubes administrator, if send email successfully, it will show the message like thie:
<img width="468" alt="migration_successful" src="https://user-images.githubusercontent.com/9430290/84164348-fd584380-aaa4-11ea-9209-6f420fd1a3c0.png">

6. Cubes administrator will receive an email like this:
<img width="762" alt="migration_request_email" src="https://user-images.githubusercontent.com/9430290/84164394-0e08b980-aaa5-11ea-90a9-921d70ca796d.png">

7. Cubes administrator logins into Kylin QA portal, and go to "Action" drop-down list in the 'Admins' column, and click 'Approve Migration' button to migrate cube or click 'Reject Migration' button to reject request.
<img width="1045" alt="appro_reject" src="https://user-images.githubusercontent.com/9430290/84167087-5c6b8780-aaa8-11ea-84f8-aed5587f3f49.png">

8. If cubes administrator click 'Reject Migration' button to reject migration request, it will send a rejected email to the migration requester:
<img width="744" alt="reject" src="https://user-images.githubusercontent.com/9430290/84167118-69887680-aaa8-11ea-8117-91d8c3473aa5.png">

9. If cubes administrator click 'Approve Migration' button to migrate cube, it will show a pop-up window:
<img width="570" alt="approve_migration" src="https://user-images.githubusercontent.com/9430290/84167492-e582be80-aaa8-11ea-8b4e-4a90e8002861.png">
After enter the target project name, and click 'Approve' button, it will start to migrate cube and send a migration approved email to the migration requester:
<img width="723" alt="approved_migration" src="https://user-images.githubusercontent.com/9430290/84168451-fed83a80-aaa9-11ea-96f6-2fb1dd9c291e.png">
If migrate successfully, it will show the message below:
<img width="469" alt="approve_migration_successfully" src="https://user-images.githubusercontent.com/9430290/84167707-27ac0000-aaa9-11ea-857b-664f338e9550.png">
And it will also send a migration completed email to the migration requester:
<img width="707" alt="completed_migration" src="https://user-images.githubusercontent.com/9430290/84168609-31823300-aaaa-11ea-9d1d-4b03524e58ab.png">

10. Go to Kylin PROD portal: [PROD Kylin](http://10.1.2.13:17777/kylin), and refresh the 'Model' tab page;

11. Find the cube you migrated from 'Model' page, the status of the migrated cube is DISABLED;<img width="1045" alt="migrated_cube" src="https://user-images.githubusercontent.com/9430290/84173308-b1f76280-aaaf-11ea-8afc-db019139ebff.png">

12. Build a segment (2012-01-01 ~ 2013-01-01) for the migrated cube:
<img width="1050" alt="migrated_cube_segment" src="https://user-images.githubusercontent.com/9430290/84176639-449a0080-aab4-11ea-925e-a160ca4880e3.png">

13. Use below sql to query on the QA env and PROD env, and compare the result:
```sql
select part_dt, sum(price) as total_sold, count(distinct seller_id) as sellers from kylin_sales
where part_dt >= '2012-09-26' and part_dt <= '2012-10-01'
group by part_dt order by part_dt;
```
The result is the same:
<img width="988" alt="query_result_qa" src="https://user-images.githubusercontent.com/9430290/84286074-cea79f00-ab70-11ea-8b66-0c4bc495a866.png">
<img width="959" alt="query_result_prod_1" src="https://user-images.githubusercontent.com/9430290/84286101-d8310700-ab70-11ea-8d9e-b50bb4521e51.png">

**Comment by zzcclp** [comment]
## Verify test cases - Case-2
1. Make sure that the cube you want to migrate on QA env is __READY__.
<img width="1370" alt="cross_mig_cube_ready" src="https://user-images.githubusercontent.com/9430290/84213867-5bf8de00-aaf4-11ea-8ade-8e30939e26b5.png">

2. Create a project on PROD env, and the project name must be the same as the one on QA env.

3. Use below command to migrate cubes from QA env to PROD env which is on the other cluster:
```
${KYLIN_HOME}/bin/kylin.sh org.apache.kylin.tool.migration.CubeMigrationCrossClusterCLI -kylinUriSrc ADMIN:KYLIN@sandbox.hortonworks.com:17070 -kylinUriDst ADMIN:KYLIN@sandbox.prod.hortonworks.com:17777 -cube kylin_sales_cube_for_mr -updateMappingPath /root/zhangzc/apache-kylin-3.1.0-qa/updateTableMapping.json -execute true -schemaOnly false -overwrite true
```
#### Common parameters description:

- kylinUriSrc: specify the source kylin uri with format user:pwd@host:port, it's required;
- kylinUriDst: specify the target kylin uri with format user:pwd@host:port, it's required;
- updateMappingPath: specify the path for the update Hive table mapping file, the format is json, see the example below:
```json
{
  "KYLIN_4485_QA.KYLIN_ACCOUNT": {
    "database": "KYLIN_4485_PROD",
    "tableName": "KYLIN_ACCOUNT"
  },
  "KYLIN_4485_QA.KYLIN_CAL_DT": {
    "database": "KYLIN_4485_PROD"
  },
  "KYLIN_4485_QA.KYLIN_CATEGORY_GROUPINGS": {
    "database": "KYLIN_4485_PROD"
  },
  "KYLIN_4485_QA.KYLIN_COUNTRY": {
    "database": "KYLIN_4485_PROD"
  },
  "KYLIN_4485_QA.KYLIN_SALES": {
    "database": "KYLIN_4485_PROD"
  }
}
```
- cube: specify the cubes which you want to migrate, separated by ',';
- hybrid: specify the hybrids which you want to migrate, separated by ',';
- project: specify the projects which you want to migrate, separated by ',';
- all: specify all projects to migrate;

**Note**: You must add only one of above four parameters;

- dstHiveCheck: specify whether to check target hive tables, the default value is true;
- overwrite: specify whether to overwrite existing cubes, the default value is false;
- schemaOnly: specify whether only migrate cube related schema, the default value is true;
- execute: specify whether it's to execute the migration, the default value is false;
- coprocessorPath: specify the path of coprocessor to be deployed, the default value is get from KylinConfigBase.getCoprocessorLocalJar();
- codeOfFSHAEnabled: specify whether to enable the namenode ha of clusters;
- distCpJobQueue: specify the mapreduce.job.queuename for DistCp job;
- distCpJobMemory: specify the mapreduce.map.memory.mb for DistCp job;
- nThread: specify the number of threads for migrating cube data in parallel;

4. If you see the below messages, it means the migration is done:
<img width="1389" alt="cross_mig_success_log" src="https://user-images.githubusercontent.com/9430290/84288175-6c03d280-ab73-11ea-9fcb-463348595a27.png">

5. Go to Kylin PROD portal and find the cube you migrated from 'Model' page, the status of the cube is READY:
<img width="1052" alt="cross_cube_ready" src="https://user-images.githubusercontent.com/9430290/84290565-68be1600-ab76-11ea-8c5d-ba5090cade76.png">

6. Use below sql to query on the QA env and PROD env, and compare the result:
```sql
select part_dt, sum(price) as total_sold, count(distinct seller_id) as sellers from kylin_sales
where part_dt >= '2012-09-26' and part_dt <= '2012-10-01'
group by part_dt order by part_dt;
```
The result is the same:
<img width="988" alt="query_result_qa" src="https://user-images.githubusercontent.com/9430290/84290660-88edd500-ab76-11ea-93e0-a367b4e22763.png">
<img width="974" alt="query_result0" src="https://user-images.githubusercontent.com/9430290/84291103-37921580-ab77-11ea-93fe-bac83fbbe43f.png">

**Comment by zzcclp** [comment]
## Verify test cases - Case-3
### Prepare data: use sample cube to test this case
1. Disable cube and purge cube if the cube is ready:
<img width="1050" alt="disable_purge_cube" src="https://user-images.githubusercontent.com/9430290/84291866-4200df00-ab78-11ea-886e-813f9053a361.png">

2. Change the data type of the below columns from date to varchar:
- the column 'CAL_DT' in table KYLIN_CAL_DT;
- the column 'PART_DT' in table KYLIN_SALES;

SQL:
use kylin_4485_prod;
ALTER TABLE KYLIN_CAL_DT CHANGE CAL_DT CAL_DT String;
ALTER TABLE KYLIN_SALES CHANGE PART_DT PART_DT String;

3. Go to Kylin portal and click 'Data Source' tab:
- select 'KYLIN_CAL_DT' table on the left frame and then click 'Reload Table' button;
- select 'KYLIN_SALES' table on the left frame and then click 'Reload Table' button;
- check the data type whether is varchar:
<img width="1382" alt="cal_dt_datatype" src="https://user-images.githubusercontent.com/9430290/84295394-1cc29f80-ab7d-11ea-9f80-8fac78f1b654.png">
<img width="1334" alt="sales_part_dt_datatype" src="https://user-images.githubusercontent.com/9430290/84295403-1f24f980-ab7d-11ea-82ac-1dd5b31a15c1.png">

### Verify
1. Edit the cube, in 'Advanced Setting' step, change the 'Encoding' of column 'KYLIN_SALES.PART_DT' from date to dict:
<img width="924" alt="change_encoding_dict" src="https://user-images.githubusercontent.com/9430290/84296146-34e6ee80-ab7e-11ea-850f-d7b7cb134dc4.png">

2. Build a segment (2012-03-01 ~ 2012-05-01):
<img width="1028" alt="change_data_type_segment1" src="https://user-images.githubusercontent.com/9430290/84328598-f6b8f180-abb4-11ea-881d-93f4ec8bc623.png">

3. Use below query sql to verify, the where clause of query sql must include 'PART_DT' column;
```sql
select part_dt, sum(price) as total_sold, count(distinct seller_id) as sellers from kylin_sales
where part_dt >= '2012-03-26' and part_dt <= '2012-04-05'
group by part_dt order by part_dt;
```
Query successfully:
<img width="1025" alt="query_segment1_result" src="https://user-images.githubusercontent.com/9430290/84328818-a4c49b80-abb5-11ea-98a7-d75a38e72c57.png">

4. Edit the cube, in 'Configuration Overwrites' step, add a property 'kylin.cube.rowkey-encoding-auto-convert=false' into cube level properties:
<img width="1011" alt="add_property_for_cube" src="https://user-images.githubusercontent.com/9430290/84331479-dab94e00-abbc-11ea-98c4-bb3d46ba284b.png">

5. Change the data type of the below columns from varchar to date:
- the column 'CAL_DT' in table KYLIN_CAL_DT;
- the column 'PART_DT' in table KYLIN_SALES;

SQL:
use kylin_4485_prod;
ALTER TABLE KYLIN_CAL_DT CHANGE CAL_DT CAL_DT Date;
ALTER TABLE KYLIN_SALES CHANGE PART_DT PART_DT Date;

6. Back to Kylin portal and click 'Data Source' tab:
- select 'KYLIN_CAL_DT' table on the left frame and then click 'Reload Table' button;
- select 'KYLIN_SALES' table on the left frame and then click 'Reload Table' button;
- check the data type whether is date:
<img width="1347" alt="cal_dt_datatype_change" src="https://user-images.githubusercontent.com/9430290/84331719-8c587f00-abbd-11ea-916d-2a86494e5d16.png">
<img width="1371" alt="part_dt_datatype_changes" src="https://user-images.githubusercontent.com/9430290/84331720-8ebad900-abbd-11ea-8356-941cc51b5cc4.png">

7. Use below query sql to verify, the where clause of query sql must include 'PART_DT' column;
```sql
select part_dt, sum(price) as total_sold, count(distinct seller_id) as sellers from kylin_sales
where part_dt >= '2012-03-26' and part_dt <= '2012-04-05'
group by part_dt order by part_dt;
```
Query successfully:
<img width="1056" alt="query_segment1_result1" src="https://user-images.githubusercontent.com/9430290/84331797-c6c21c00-abbd-11ea-85fa-4aeada80c8a1.png">

8. Build a segment again (2012-05-01 ~ 2013-01-01):
<img width="1034" alt="segment2" src="https://user-images.githubusercontent.com/9430290/84334154-418e3580-abc4-11ea-943d-41573bf9dbeb.png">

9. Use below query sql to verify, the where clause of query sql must include 'PART_DT' column;
```sql
select part_dt, sum(price) as total_sold, count(distinct seller_id) as sellers from kylin_sales
where part_dt >= '2012-03-26' and part_dt <= '2012-06-20'
group by part_dt order by part_dt;
```
Query successfully:
<img width="1035" alt="query_segment2_result" src="https://user-images.githubusercontent.com/9430290/84335621-d8102600-abc7-11ea-93f0-e6aaea632161.png">

10. Merge two segments build in step 2 and 8:
<img width="1044" alt="merge_segment" src="https://user-images.githubusercontent.com/9430290/84336825-aea4c980-abca-11ea-88bf-2c4709b00595.png">

11. Use below query sql to verify, the where clause of query sql must include 'PART_DT' column;
```sql
select part_dt, sum(price) as total_sold, count(distinct seller_id) as sellers from kylin_sales
where part_dt >= '2012-03-26' and part_dt <= '2012-06-20'
group by part_dt order by part_dt;
```
Query successfully:
<img width="1031" alt="query_merged_segment_result" src="https://user-images.githubusercontent.com/9430290/84336900-e57adf80-abca-11ea-87cd-357cb005aa29.png">

Verified done.

**Comment by zzcclp** [comment]
## Add document in Kylin website
To do.

**Comment by zzcclp** [comment]
## Summary
All functions are verified done, this pr can be merged.

**Comment by kyotoYaho** [comment]
Great doc

**Comment by shaofengshi** [comment]
Great! Thanks Zhichao!
